name: Build and publish Docker image
on:
  # Trigger the workflow on push or pull request,
  # for the develop branch and all new tags
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Fetch Prune Unshallow Tags
      run: git fetch --prune --unshallow --tags
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Extract commit hash
      shell: bash
      run: echo "##[set-output name=hash;]$(git rev-parse --short ${GITHUB_SHA})"
      id: extract_hash
    - name: Extract latest tag
      shell: bash
      run: echo "RELEASE_VERSION="$(git describe --tags --abbrev=0 ${GITHUB_SHA}) >> $GITHUB_ENV
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      env:
        GIT_BRANCH: ${{ steps.extract_branch.outputs.branch }}
        GIT_REVISION: ${{ steps.extract_hash.outputs.hash }}
      with:
        name: c2dhunilu/legionnaire
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        buildargs: GIT_BRANCH,GIT_REVISION
        tags: "latest"
